# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Kuliah\Semester 7\RPP\tugas-1-kbs-rpp\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 464)
        self.predictButton = QtWidgets.QPushButton(Form)
        self.predictButton.setGeometry(QtCore.QRect(40, 380, 721, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.predictButton.setFont(font)
        self.predictButton.setObjectName("predictButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 721, 51))
        self.label.setStyleSheet("font-size: 40px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(40, 100, 721, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.pm10_input = QtWidgets.QLineEdit(self.groupBox)
        self.pm10_input.setGeometry(QtCore.QRect(100, 60, 231, 30))
        self.pm10_input.setObjectName("pm10_input")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.so2_input = QtWidgets.QLineEdit(self.groupBox)
        self.so2_input.setGeometry(QtCore.QRect(100, 110, 231, 30))
        self.so2_input.setObjectName("so2_input")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(360, 60, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.o3_input = QtWidgets.QLineEdit(self.groupBox)
        self.o3_input.setGeometry(QtCore.QRect(430, 60, 261, 30))
        self.o3_input.setObjectName("o3_input")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(360, 110, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.no2_input = QtWidgets.QLineEdit(self.groupBox)
        self.no2_input.setGeometry(QtCore.QRect(430, 110, 261, 30))
        self.no2_input.setObjectName("no2_input")
        self.co_input = QtWidgets.QLineEdit(self.groupBox)
        self.co_input.setGeometry(QtCore.QRect(100, 160, 591, 30))
        self.co_input.setObjectName("co_input")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setGeometry(QtCore.QRect(40, 340, 571, 30))
        self.result_label.setStyleSheet("font-weight: 500;\n"
"font-size: 20px;\n"
"")
        self.result_label.setObjectName("result_label")
        self.groupBox.raise_()
        self.predictButton.raise_()
        self.label.raise_()
        self.result_label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.predictButton.setText(_translate("Form", "Predict"))
        self.label.setText(_translate("Form", " Air Quality Model Prediction"))
        self.groupBox.setTitle(_translate("Form", "Input Parameter"))
        self.label_2.setText(_translate("Form", "PM10"))
        self.label_3.setText(_translate("Form", "SO2"))
        self.label_4.setText(_translate("Form", "O3"))
        self.label_5.setText(_translate("Form", "NO2"))
        self.label_6.setText(_translate("Form", "CO"))
        self.result_label.setText(_translate("Form", "Air Quality :"))
